docs: documentation
cerejeiros/mobile pull request #16
Opened 2023-04-27 15:30 UTC by BeyondMagic

Para fechar #11... deverá ter merge quando acabarmos com [1.0 - DeS](https://github.com/cerejeiros/mobile/milestone/1).

Para contribuir:
+ commits devem se restringir ao arquivo [/docs/documentation.md : **documentacao/docs**](https://github.com/cerejeiros/mobile/blob/documentacao/docs/docs/documentation.md)

2023-04-27 19:00 UTC, Neoprot approved these changes

2023-04-27 22:33 UTC, kaioenzo requested changes
Apenas correção de erro ortográfico

2023-04-27 22:33 UTC, kaioenzo commented on docs/documentation.md
> +Projeto de DeS (2023.1) com o professor Sérgio Freitas da FGA (UnB) [[email de contado]](mailto:sergiofreitas@unb.br).
Acho que poderia ser o nome completod a disciplina, e corrija `email de contato` aqui!

2023-04-27 23:15 UTC, BeyondMagic commented on docs/documentation.md
> +Projeto de DeS (2023.1) com o professor Sérgio Freitas da FGA (UnB) [[email de contado]](mailto:sergiofreitas@unb.br).
@Neoprot arruma!

2023-04-28 21:53 UTC, Neoprot commented on docs/documentation.md
> +Projeto de DeS (2023.1) com o professor Sérgio Freitas da FGA (UnB) [[email de contado]](mailto:sergiofreitas@unb.br).
Corrigido!

2023-04-28 21:53 UTC, kaioenzo approved these changes

2023-04-28 21:53 UTC, kaioenzo approved these changes

2023-04-28 21:54 UTC, merged