shared: add tasks, habits, and routine
cerejeiros/mobile pull request #40
Opened 2023-06-23 19:49 UTC by BeyondMagic

para começar a tela de status mais facilmente

- [x] tipos de tasks, habits, routines.
- [ ] supabase habits
- [ ] supabase routines
- [ ] variaveis globais para uso indepedente de tela.
https://stackoverflow.com/a/53292805

2023-06-25 17:20 UTC, Neoprot approved these changes

2023-06-25 17:20 UTC, Neoprot commented on src/types/shared.ts
> +    priority: "urgent" | "medium" | "low";
Como é um Hábito, será que urgente seria o certo? Não seria melhor High | Medium | low?

2023-06-25 17:20 UTC, Neoprot commented on src/types/shared.ts
> +    repeated: "daily" | "monthly" | "yearly" | number;
Será que vale colocar anualmente? Como seria um hábito anual? Uma vez ao ano? Acho melhor ser Daily | weekly | monthly

2023-06-25 17:37 UTC, BeyondMagic commented on src/types/shared.ts
> +    priority: "urgent" | "medium" | "low";
sim sim

2023-06-25 17:40 UTC, BeyondMagic commented on src/types/shared.ts
> +    repeated: "daily" | "monthly" | "yearly" | number;
Não é um hábito nesse caso, é uma Task apenas; tem "tasks" que de fato são anuais para algumas pessoas, aí deixa o anualmente porque é um número bem grande de ser calculado pelo usuário. E adiciono o `"weekly"`.

2023-07-06 05:58 UTC, BeyondMagic commented
Checa por favor o workflow do prettier, @kaioenzo 

Teste com debug do Github: https://github.com/cerejeiros/mobile/actions/runs/5472000683/jobs/9963824432

![image](https://github.com/cerejeiros/mobile/assets/51831435/8bf59b14-e085-4e10-b737-a50538ee3bad)

2023-07-06 18:45 UTC, Neoprot commented on src/screens/profile/User.tsx
> +    // const [oldUserData, setUserData] = useState<UserData | undefined>(undefined);
Comentários...

2023-07-06 18:45 UTC, Neoprot approved these changes

2023-07-06 23:24 UTC, NATANGOATOSO approved these changes

2023-07-08 01:07 UTC, Luizaxx approved these changes

2023-07-08 21:29 UTC, kaioenzo requested changes
Apenas um comentário breve, no geral, ótimo trabalho guys!!

2023-07-08 21:29 UTC, kaioenzo commented on src/screens/signup/input.tsx
>          console.log(isloading);
Devemos evitar console.log()

2023-07-08 21:34 UTC, kaioenzo approved these changes

2023-07-08 21:36 UTC, merged